### ISSUE TITLE
firefox version please

### ISSUE THREAD

**Issue by gmankab** [cjmaxik/more-boosty#10]

**Comment by cjmaxik** [comment]
На данный момент версия для Firefox не планируется.

- Firefox не поддерживает некоторые важные функции расширения (PiP API и background service workers).
- Для частичной поддержки потребуется сильно изменить рабочий процесс.
- Нет спроса на версию для Firefox.

---

There are currently no plans to support Firefox.

- Firefox does not support some crucial functions (PiP API and background service workers).
- Partial support will require an extensive tooling changes.
- There is no demand for the Firefox version.

**Comment by gmankab** [comment]
:(
