### ISSUE TITLE
Пропала кнопка Скачать в Бусти

### ISSUE THREAD

**Issue by Ypdes** [cjmaxik/more-boosty#15]
Например, здесь: https://boosty.to/m0rtymerr/posts/0272fa04-321d-489b-9f82-d81acd80143f

Раньше была под видео, сейчас не вижу. 

Версия 23.5.5

(Кстати, новую версию не могу скачать с Гугла, пишет «Installation currently unavailable»

![image](https://github.com/cjmaxik/more-boosty/assets/134853152/1b67de5e-a25f-4004-a5f7-7094c78bfa6a)

* Было бы хорошо сразу crx скачать.

**Comment by cjmaxik** [comment]
Старая версия само собой не будет поддерживать последние изменения на Бусти.
Расширение доступно для скачивания через Web Store, данная ошибка на стороне браузера. 

Для скачивания crx можно воспользоваться любым онлайн-сервисом, либо [собрать самому](https://github.com/cjmaxik/more-boosty?tab=readme-ov-file#%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2%D1%80%D1%83%D1%87%D0%BD%D1%83%D1%8E) и загрузить как распакованное расширение (обновлять придется вручную).
